import * as fs from 'node:fs';
import * as path from 'node:path';
import { Client } from 'pg';
import type { DesktopConfig } from './config';
import { log } from './log';

// embedded-postgres is ESM-only; imported dynamically (await import) inside
// start() since this is a CommonJS module. Held loosely-typed (thin wrapper).
type EmbeddedPostgresInstance = {
  initialise: () => Promise<void>;
  start: () => Promise<void>;
  stop: () => Promise<void>;
  createDatabase: (name: string) => Promise<void>;
};

/**
 * Manages an embedded PostgreSQL instance bundled inside the app — no Docker, no
 * system Postgres. First launch initialises a data dir under the user's app-data
 * folder; every launch starts the server, ensures the DB exists, and applies any
 * pending SQL migrations.
 */
export class DatabaseManager {
  private pg?: EmbeddedPostgresInstance;

  constructor(private readonly cfg: DesktopConfig) {}

  async start(): Promise<void> {
    const firstRun = !fs.existsSync(path.join(this.cfg.dataDir, 'PG_VERSION'));
    fs.mkdirSync(this.cfg.dataDir, { recursive: true });

    const { default: EmbeddedPostgresCtor } = (await import('embedded-postgres')) as {
      default: new (opts: Record<string, unknown>) => EmbeddedPostgresInstance;
    };
    this.pg = new EmbeddedPostgresCtor({
      databaseDir: this.cfg.dataDir,
      user: this.cfg.pgUser,
      password: this.cfg.pgPassword,
      port: this.cfg.pgPort,
      persistent: true,
    });

    if (firstRun) {
      log('First run — initialising PostgreSQL cluster…');
      await this.pg.initialise();
    }
    log(`Starting PostgreSQL on 127.0.0.1:${this.cfg.pgPort}…`);
    await this.pg.start();

    if (firstRun) {
      log('Creating database…');
      await this.pg.createDatabase(this.cfg.pgDatabase);
    }

    await this.applyMigrations();
  }

  /**
   * Apply pending SQL migrations directly via a Postgres client.
   *
   * We deliberately do NOT shell out to the Prisma CLI: with pnpm the CLI's own
   * transitive deps (@prisma/engines) aren't present in the bundled API, and the
   * CLI is a heavy dev-only tool. The migration SQL (generated by Prisma at build
   * time, in prisma/migrations/<name>/migration.sql) is applied here, tracked in
   * a small _pe_migrations table so it is idempotent and supports future
   * migrations. The API itself uses @prisma/client (the generated client), which
   * is bundled separately.
   */
  private async applyMigrations(): Promise<void> {
    const migrationsDir = path.join(this.cfg.prismaDir, 'migrations');
    if (!fs.existsSync(migrationsDir)) {
      log(`No migrations dir at ${migrationsDir} — skipping`, 'warn');
      return;
    }

    const client = new Client({ connectionString: this.cfg.databaseUrl });
    await client.connect();
    try {
      await client.query(
        'CREATE TABLE IF NOT EXISTS "_pe_migrations" (name text PRIMARY KEY, applied_at timestamptz DEFAULT now())',
      );
      const applied = new Set(
        (await client.query('SELECT name FROM "_pe_migrations"')).rows.map((r) => r.name as string),
      );

      const pending = fs
        .readdirSync(migrationsDir)
        .filter((d) => fs.existsSync(path.join(migrationsDir, d, 'migration.sql')))
        .sort()
        .filter((d) => !applied.has(d));

      if (pending.length === 0) {
        log('Database schema is up to date.');
        return;
      }

      for (const name of pending) {
        log(`Applying migration ${name}…`);
        const sql = fs.readFileSync(path.join(migrationsDir, name, 'migration.sql'), 'utf8');
        await client.query(sql); // simple-query protocol runs multiple statements
        await client.query('INSERT INTO "_pe_migrations"(name) VALUES ($1)', [name]);
      }
      log(`Applied ${pending.length} migration(s).`);
    } finally {
      await client.end();
    }
  }

  async stop(): Promise<void> {
    if (!this.pg) return;
    try {
      log('Stopping PostgreSQL…');
      await this.pg.stop();
    } catch (err) {
      // Never let shutdown cleanup crash the app.
      log(`PostgreSQL stop error (ignored): ${(err as Error).message}`, 'warn');
    }
  }
}
