/* eslint-disable @next/next/no-img-element */

/**
 * The PartEngine logo + wordmark. Sourced from /public/logo.png (regenerated by
 * apps/desktop/scripts/make-icons.mjs). Plain <img> keeps it usable in both the
 * Next app and the static Electron contexts without next/image's loader.
 */
export function Logo({
  size = 28,
  showWordmark = true,
  className = '',
}: {
  size?: number;
  showWordmark?: boolean;
  className?: string;
}) {
  return (
    <div className={`flex items-center gap-2 ${className}`}>
      <img src="/logo.png" alt="PartEngine" width={size} height={size} className="shrink-0" />
      {showWordmark && <span className="text-lg font-bold">PartEngine</span>}
    </div>
  );
}
